export const GET_PROFILES = "GET_PROFILES",
  ADD_PROFILE = "ADD_PROFILE",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  DELETE_PROFILE = "DELETE_PROFILE",
  CLEAR_PROFILES = "CLEAR_PROFILES";

export const DELETE_SESSION = "DELETE_SESSION";