export const LOADING = "LOADING", SUCCESS = "SUCCESS", ERROR = "ERROR";

export const GET_PROFILES = "GET_PROFILES",
  ADD_PROFILE = "ADD_PROFILE",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  DELETE_PROFILES = "DELETE_PROFILES";

export const DELETE_SESSION = "DELETE_SESSION";
